### ISSUE TITLE
brew install fails on 2018 MB, High Sierra 10.13.4

### ISSUE THREAD

**Issue by bryanskene** [saulpw/homebrew-vd#1]
bryan@Bryans-MB-Pro:~$ brew install saulpw/vd/visidata

[snip]

######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/visidata--homebrew-virtualenv-20180525-92795-19ud9km/target --single-version-extern
Last 15 lines from /Users/bryan/Library/Logs/Homebrew/visidata/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/visidata--homebrew-virtualenv-20180525-92795-19ud9km/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

**Comment by anjakefala** [comment]
Hi Bryan!

That is annoying :( Unfortunately, [python environments are a bit of an environmental disaster](https://m.xkcd.com/1987/), but I hope we manage to debug this.

Can you please share with me the outputs of `brew doctor` and `brew config`?

And also, the output of `python -c "import sys; print sys.path"`?

**Comment by bryanskene** [comment]
bryan@Bryans-MB-Pro:~$ brew install setuptools
Error: No available formula with the name "setuptools" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
bryan@Bryans-MB-Pro:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python
  wireshark

Warning: Your XQuartz (2.7.7) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/docker-credential-osxkeychain.backup
  /usr/local/bin/hyperkit.backup
  /usr/local/bin/notary.backup
  /usr/local/bin/vpnkit.backup
  /usr/local/etc/bash_completion.d/_brew_services
  /usr/local/opt/minicom

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install libmaxminddb libunistring lua@5.1 pcre

Run `brew missing` for more details.


bryan@Bryans-MB-Pro:~$ brew config
HOMEBREW_VERSION: 1.6.6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e4c02fafdaef5676cf40dd6d16e74976cf54b265
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5431542903ee2d6b7b9307165edcde44bcff7b32
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.8.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.3.1
XQuartz: 2.7.7 => /opt/X11


bryan@Bryans-MB-Pro:~$ python -c "import sys; print sys.path"
['', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']

**Comment by anjakefala** [comment]
For the record. I had suggested the following series of commands:

1) Is there /usr/local/Frameworks and is it owned by you?  Otherwise:

```
sudo mkdir -p /usr/local/Frameworks
sudo chown -R $(whoami) /usr/local/*
```

(in reference to https://github.com/Homebrew/homebrew-core/issues/20985)

2) To use Python3 for install instead of system default Python2: 

```
brew install python3
brew link python3
```

3) Then try installing visidata again:

```
brew install saulpw/vd/visidata
```

The issue persisted.

I then suggested:

1) 
```
    sudo mkdir -p /usr/local/include
    sudo chown -R $(whoami) $(brew --prefix)/*
```

(Reference: https://github.com/kickstarter/laptop/pull/49)

```
   brew install saulpw/vd/visidata
```

2) If that fails

```
    brew install python
    brew postinstall python
    brew link python
```

(noting if there are errors in the output)
then

```
    brew install saulpw/vd/visidata
```

(Reference: https://github.com/Homebrew/homebrew-python/issues/216 and https://brew.sh/2018/04/09/homebrew-1.6.0/)

**Comment by bryanskene** [comment]
bryan@Bryans-MB-Pro:/usr/local$ brew install python
Warning: python 3.6.5 is already installed and up-to-date
To reinstall 3.6.5, run `brew reinstall python`
bryan@Bryans-MB-Pro:/usr/local$ brew postinstall python
==> Postinstalling python
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3.6.5/bin --i
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3.6.5/bin --i
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/3.6.5/bin --i
bryan@Bryans-MB-Pro:/usr/local$ brew link python
Warning: Already linked: /usr/local/Cellar/python/3.6.5
To relink: brew unlink python && brew link python

... then possible success?


bryan@Bryans-MB-Pro:/usr/local$ brew install saulpw/vd/visidata
==> Installing visidata from saulpw/vd
==> Downloading https://files.pythonhosted.org/packages/4f/f6/01acfae53ae901756bc7778fc8c6f1ee70d442b5190f8bfe7d54dd35bb19/visidata-1.2.tar.gz
Already downloaded: /Users/bryan/Library/Caches/Homebrew/visidata-1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
Already downloaded: /Users/bryan/Library/Caches/Homebrew/visidata--homebrew-virtualenv-16.0.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/visidata--homebrew-virtualenv-20180530-15232-7msfb5/target --single-version-externa
==> python3 -s /tmp/visidata--homebrew-virtualenv-20180530-15232-7msfb5/target/bin/virtualenv -p python3 /usr/local/Cellar/visidata/1.2/libexec
==> Downloading https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--six-20180530-15232-1tsl
==> Downloading https://files.pythonhosted.org/packages/54/bb/f1db86504f7a49e1d9b9301531181b00a1c7325dc85a29160ee3eaa73a54/python-dateutil-2.6.1.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--python-dateutil-2018053
==> Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--et-xmlfile-20180530-152
==> Downloading https://files.pythonhosted.org/packages/9b/fa/40beb2aa43a13f740dd5be367a10a03270043787833409c61b79e69f1dfd/jdcal-1.3.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--jdcal-20180530-15232-cb
==> Downloading https://files.pythonhosted.org/packages/8c/75/c4e557207c7ff3d217d002d4fee32b4e5dbfc5498e2a2c9ce6b5424c5e37/openpyxl-2.4.9.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--openpyxl-20180530-15232
==> Downloading https://files.pythonhosted.org/packages/86/cf/bb010f16cefa8f26ac9329ca033134bcabc7a27f5c3d8de961bacc0f80b3/xlrd-1.1.0.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--xlrd-20180530-15232-17j
==> Downloading https://files.pythonhosted.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--idna-20180530-15232-1xk
==> Downloading https://files.pythonhosted.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--certifi-20180530-15232-
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--chardet-20180530-15232-
==> Downloading https://files.pythonhosted.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--urllib3-20180530-15232-
==> Downloading https://files.pythonhosted.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata--requests-20180530-15232
==> /usr/local/Cellar/visidata/1.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/visidata-20180530-15232-eitovq/vi
🍺  /usr/local/Cellar/visidata/1.2: 1,707 files, 16.6MB, built in 24 seconds
bryan@Bryans-MB-Pro:/usr/local$

**Comment by saulpw** [comment]
Well, after all that, can you run `vd` (without a special PATH and PYThONPATH)?

**Comment by bryanskene** [comment]
OK so that worked and just in time for Saul to come over tomorrow. (we were running out of a clone of the repo yesterday)

Thank you Anja!

**Comment by anjakefala** [comment]
!!!

<(^____^)>
