### ISSUE TITLE
Tap needs updating for latest release (v2.10.1)

### ISSUE THREAD

**Issue by scotthmurray** [saulpw/homebrew-vd#13]
This line points to an older version (2.8):

https://github.com/visidata/homebrew-vd/blob/HEAD/Formula/visidata.rb#L6

Thanks!

**Comment by anjakefala** [comment]
This is intentional! We only update the tap when we have a very stable release. Homebrew forces people to update their package, so stability is a lot more important than for `PyPI` where they can always install an earlier version.

**Comment by scotthmurray** [comment]
OK thank you! Much appreciated.
