### ISSUE TITLE
Fails to start vd after update

### ISSUE THREAD

**Issue by vincent-octo** [saulpw/homebrew-vd#14]
Today my visidata got updated when I ran `brew upgrade`.

Now, when starting vd or opening a file with vd I get the error:
```
ModuleNotFoundError: No module named 'importlib_metadata'
```

For example:

```
~$ vd
Traceback (most recent call last):
  File "/opt/homebrew/bin/vd", line 6, in <module>
    visidata.main.vd_cli()
  File "/opt/homebrew/Cellar/visidata/2.11/libexec/lib/python3.10/site-packages/visidata/main.py", line 354, in vd_cli
    rc = main_vd()
  File "/opt/homebrew/Cellar/visidata/2.11/libexec/lib/python3.10/site-packages/visidata/main.py", line 212, in main_vd
    vd.loadConfigAndPlugins(args)
  File "/opt/homebrew/Cellar/visidata/2.11/libexec/lib/python3.10/site-packages/visidata/settings.py", line 377, in loadConfigAndPlugins
    from importlib_metadata import entry_points  # a backport which supports < 3.8 https://github.com/pypa/twine/pull/732
ModuleNotFoundError: No module named 'importlib_metadata'
```

I am guessing this is due to `importlib_metadata` not being installed on my machine.
I am not sure how the packaging goes in this situation.
Should this module be added to `visidata.rb`?

It looks like this `importlib_metadata` module was added upstream in the last few months:
https://github.com/saulpw/visidata/blob/0cd41c6d052ff1a1dcaf4548def4378eb1b96480/CHANGELOG.md?plain=1#L139

**Comment by anjakefala** [comment]
Thanks for letting me know! I maintain the brew, but do not have a Mac machine to test on. I will get that sorted!

**Comment by anjakefala** [comment]
Formula updated. Could you please test and let me know how it goes?

**Comment by vincent-octo** [comment]
I did a `brew upgrade` but visidata didn't upgrade.

I think this is because the version of visidata didn't change so Homebrew doesn't bother updating it.

```
$ brew upgrade
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 4b3d64d30 to 1e4ae4ef7.
Updated 1 tap (saulpw/vd).
```

```
$ brew upgrade visidata
Warning: saulpw/vd/visidata 2.11 already installed
```


However, I edited the visidata formula myself and changed it likeso:

```diff
diff --git a/Formula/visidata.rb b/Formula/visidata.rb
index 657602a..7f55a88 100644
--- a/Formula/visidata.rb
+++ b/Formula/visidata.rb
@@ -3,7 +3,7 @@ class Visidata < Formula
   desc "Terminal utility for exploring and arranging tabular data"
   homepage "https://visidata.org/"
   url "https://files.pythonhosted.org/packages/4e/45/75bec1b89ec27b0e74f84da2f036a20f9ed7d15c4e53283efb12cb355ede/visidata-2.11.tar.gz"
-  version "2.11"
+  version "2.11_1"
   sha256 "c09ecb65025dc9d6513bfd5e5aff9c430ffc325cc183b81abf5f2df5a96b66b3"

   depends_on "python"
```

After that, a `brew upgrade` actually updated visidata and now running `vd` works.

However, after some looking around I don't think this is the proper way to do this. Homebrew provides [a `revision` parameter](https://docs.brew.sh/Formula-Cookbook#formulae-revisions) and it looks like it should be used here:

```diff
diff --git a/Formula/visidata.rb b/Formula/visidata.rb
index 657602a..5cb10d3 100644
--- a/Formula/visidata.rb
+++ b/Formula/visidata.rb
@@ -5,6 +5,7 @@ class Visidata < Formula
   url "https://files.pythonhosted.org/packages/4e/45/75bec1b89ec27b0e74f84da2f036a20f9ed7d15c4e53283efb12cb355ede/visidata-2.11.tar.gz"
   version "2.11"
   sha256 "c09ecb65025dc9d6513bfd5e5aff9c430ffc325cc183b81abf5f2df5a96b66b3"
+  revision 1

   depends_on "python"
```

This also worked in my testing.

**Comment by anjakefala** [comment]
Thanks @vincent-octo! That was very helpful. I added the revision parameter.
